name: Update gist
on:
  watch:
    types: started
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: beer-on-ice/netease-music-box
      - run: yarn install
      - name: Update gist
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.MUSIC_GH_TOKEN }}
          GIST_ID: ${{ secrets.MUSIC_GIST_ID }}
          USER_ID: ${{ secrets.MUSIC_USER_ID }}
          USER_TOKEN: ${{ secrets.MUSIC_USER_TOKEN }}
