name: Social Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: beer-on-ice/social-readme@master
        with:
          blog_rss_link: https://ly.565869.xyz/atom.xml     #your blog rss link
          blog_limit: 5 # blog数量
          douban_name: sun0225SUN    
          douban_limit: 5 # 豆瓣最新动态数量
          commit_message: Updated social rss by social-readme # commit说明
